name: Generate

on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - run: php generator.php
      - name: Archive generated static site
        uses: actions/upload-artifact@v3
        with:
          name: eimf-static-site
          path: bin/*
